### acessando via get
GET http://localhost:3000/subscribers
### 
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "userName": "Fabricia Pires Bela3",
    "userChanel": "hcodebrasil"
}
###
GET http://localhost:3000/subscribers/5f6fbd243058e339d7eb4ac0
###
DELETE http://localhost:3000/subscribers/5f6fbd243058e339d7eb4ac0
###
PATCH http://localhost:3000/subscribers/5f6bc0e6cc465a85bbb6a3f2
Content-Type: application/json

{
    "userName": "Fabricia P. Bela"
}

